### ISSUE TITLE
I fail to run the app

### ISSUE THREAD

**Issue by harryprince** [nnmware/nnmware#2]
I follow your command step by step,in my virtualenv,but I fail to run the app.

```
sudo python manage.py runserver
```
```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/Users/harryzhu/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named nnmware
```

**Comment by nnmware** [comment]
Hello.
You don't have 'nnwmare' in python path.
Try

cd /Users/harryzhu/BaiduPan/Github/PycharmProjects/test/lib/python2.7/site-packages/
git clone https://github.com/nnmware/nnmware.git
